Add OpenTSDB as a fully managed Ambari service
hdinsight/Iaas-Applications pull request #5
Opened 2016-10-14 02:34 UTC by jamesbak

This addition adds the preeminent OSS TSDB OpenTSDB as a fully managed Ambari service. It also adds ARM templates to automate the deployment of a cluster featuring this service.

Please add the attached tarball to https://hdiconfigactions.blob.core.windows.net/linuxhueconfigactionv01/OPENTSDB.tar.gz
[OPENTSDB.tar.gz](https://github.com/hdinsight/Iaas-Applications/files/528548/OPENTSDB.tar.gz)

2016-10-14 23:18 UTC, ezubatov approved these changes

2016-10-14 23:38 UTC, ezubatov requested changes

2016-10-14 23:38 UTC, ezubatov commented on OpenTSDB/deployment/install-opentsdb.sh
> +opentsdb_tar_file_uri=https://hdiconfigactions.blob.core.windows.net/linuxhueconfigactionv01/$opentsdb_tar_file
THis container is only for HUE related scripts:
https://hdiconfigactions.blob.core.windows.net/linuxhueconfigactionv01

Can you please put a tarball in the same folder with your installation scripts on the github?

2016-10-17 18:25 UTC, ezubatov approved these changes

2016-10-17 22:39 UTC, travismc1 commented
Can everything under the /deployment folder be moved up to the root under /OpenTSDB. This keeps the structure in line with all of our other templates

2016-10-24 21:28 UTC, jamesbak commented
Updated directory structure as per review comments

2016-11-03 18:59 UTC, ezubatov approved these changes

2016-11-03 19:00 UTC, merged